##
# Example:
#  $ ansible-playbook aws-iac-context-rhel-environment.yml --ask-vault-pass
#  $ ansible-playbook aws-iac-context-rhel-environment.yml -t ansibletower
#  $ ansible-playbook aws-iac-context-rhel-environment.yml -t ansibletowerkeys
#  $ ansible-playbook aws-iac-context-rhel-environment.yml -t generalsubs
#  $ ansible-playbook aws-iac-context-rhel-environment.yml -t classroom
#  $ ansible-playbook aws-iac-context-rhel-environment.yml -t users --ask-vault-pass
##

- hosts: localhost
  connection: local
  gather_facts: False

  tags:
    - ansibletower
    - ansibletowerkeys
    - generalsubs
    - classroom
    - users

  vars:
    environment: "{{ ENV | default('preproduction')}}"
    version: "{{ VER | default('latest') }}"
    inventory_dict: {}

  vars_files:
    - "./vars/aws-{{ environment }}-{{ version }}.yml"

  tasks:
    - name: Extract EC2 instance information
      include_role:
        name: iac_aws_instance
      vars:
        action: add-public-ip-inventory
        instance: "{{ item.name }}"
        project: "{{ project_id }}"
        group: "ansiblenodes"
      loop: "{{ instances }}"


- hosts: ansiblenodes
  user: ec2-user
  become: true

  tags:
    - generalsubs
  
  vars:
    ansible_ssh_private_key_file: ~/Documents/ansiblepoc.pem

  vars_prompt:
    - name: "rh_cdn_user"
      prompt: "Enter REDHAT CDN user"
    - name: "rh_cdn_pass"
      prompt: "Enter REDHAT CDN pasword"

  tasks:

    - name: Register Red Hat instance with auto-subscribe
      redhat_subscription:
        state: present
        username: "{{ rh_cdn_user }}"
        password: "{{ rh_cdn_pass }}"
        force_register: true
      when:
        - ansible_facts.os_family == "RedHat"
      ignore_errors: true

    - name: Attach auto subscription
      shell: subscription-manager attach --auto
      when:
        - ansible_facts.os_family == "RedHat"

    - name: Install packages
      package:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - mariadb
        - python3-PyMySQL

    - name: Change SSH configuration pass auth
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication '
        line: 'PasswordAuthentication yes'
      notify: Restart SSHD

  handlers:

    - name: Restart SSHD
      service:
        name: sshd
        state: restarted
        enabled: yes


- hosts: student*
  user: ec2-user
  become: true

  vars_files:
    - "./vars/vault-vars.yml"

  tags:
    - users

  vars:
    ansible_ssh_private_key_file: ~/Documents/ansiblepoc.pem

  tasks:
  
    - debug:
        var: inventory_hostname
  
    - name: Generate complex password
      set_fact:
        new_user_strong_pass: "{{ new_user_pass_prefix }}{{ inventory_hostname }}"

    - name: Generate password hash sha512
      set_fact:
        new_hash_pass: "{{ new_user_strong_pass | password_hash('sha512', new_user_secret ) }}"

    - name: Create user
      user:
        name: "{{ inventory_hostname }}"
        password: "{{ new_hash_pass }}"
        group: wheel



- hosts: classroom
  user: ec2-user
  become: true

  tags:
    - classroom

  vars:
    ansible_ssh_private_key_file: ~/Documents/ansiblepoc.pem

  tasks:
    - name: Install package http
      package:
        name: httpd
        state: present
    - name: Enable and Up httpd
      service:
        name: httpd
        state: started
        enabled: yes


- hosts: ansibletower01
  user: ec2-user
  become: true

  tags:
    - ansibletower

  vars:
    ansible_ssh_private_key_file: ~/Documents/ansiblepoc.pem

  tasks:
    - shell: subscription-manager repos --enable ansible-2.9-for-rhel-8-x86_64-rpms

    - name: Install packages 
      package:
        name: "{{ item }}"
        state: present
      loop:
        - ansible
        - wget

- hosts: ansibletower*
  user: ec2-user
  become: true

  tags:
    - ansibletowerkeys

  vars:
    ansible_ssh_private_key_file: ~/Documents/ansiblepoc.pem

  tasks:
    - name: Copy SSH keys (Pub)
      copy:
        src: ~/Documents/tower_cluster.pem.pub
        dest: /root/.ssh/id_rsa.pub
        owner: root
        group: root
        mode: '0644'

    - name: Copy SSH keys (Priv)
      copy:
        src: ~/Documents/tower_cluster.pem
        dest: /root/.ssh/id_rsa
        owner: root
        group: root
        mode: '0400'

    - name: Copy SSH keys (Authorized)
      copy:
        src: ~/Documents/tower_cluster.pem.pub
        dest: /root/.ssh/authorized_keys
        owner: root
        group: root
        mode: '0644'
